name: singularity-deploy-test

# run on creation of a release tag
on:
  pull_request: []

jobs:
  builder:
    name: Test Container Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Latest Tag
        run: |
            git fetch --tags
            latest_tag=$(git tag | tail -1)
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV
            start_commit=$(git rev-list --max-parents=0 HEAD)
            echo $start_commit
      - uses: eWaterCycle/setup-singularity@v6
        with:
          singularity-version: 3.7.1
      - name: Build the singularity containers
        run: |
            repo=$(echo "${GITHUB_REPOSITORY/\//-}")

            start_commit="${latest_tag}"
            if [ "${start_commit}" == "" ]; then
              echo "in"
              start_commit=$(git rev-list --max-parents=0 HEAD)
            fi
            echo $start_commit

            recipes=$(git diff --diff-filter=AM --name-only HEAD $start_commit | { grep Singularity || [[ $? == 1 ]]; })
            echo $recipes
            # For each Singularity* container, build based on the prefix (tag) 
            for recipe in $recipes; do
                echo "Building $recipe"
                tag=$(echo "${recipe/*Singularity\./}")
                # If we find empty, use latest
                if [ "$tag" == "Singularity" ]; then
                    tag=latest
                fi
                # Build the container and name by tag
                echo "Tag is $tag."
                container="$repo:$tag.sif"
                singularity build --fakeroot container.sif "$recipe"
                if [ "$?" == "0" ]; then
                    echo "Successfully built container $container."                
                    mv container.sif "$container"
                else
                    echo "There was an issue building $container."          
                fi                
            done
      - name: Run Additional Tests
        run: |
          echo "Run any additional tests here."
