name: singularity-deploy-test

# run on creation of a release tag
on:
  pull_request: []

jobs:
  builder:
    name: Test Container Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: eWaterCycle/setup-singularity@v6
        with:
          singularity-version: 3.7.1
      - name: Build the singularity containers
        run: |
            echo "0"
            repo=$(echo "${GITHUB_REPOSITORY/\//-}")
            echo "1"
            latest_tag=$(git describe --tags --abbrev=0)
            echo "2"
            start_commit="$latest_tag"
            echo "3"
            if [ "$start_commit" == "" ]; then
              start_commit=$(git rev-list --max-parents=0 HEAD)
            fi
            echo "4"
            recipes=$(git diff --diff-filter=AM --name-only HEAD $start_commit | grep Singularity)
            echo "5"
            # For each Singularity* container, build based on the prefix (tag) 
            for recipe in $recipes; do
                echo "Building $recipe"
                tag=$(echo "${recipe/*Singularity\./}")
                # If we find empty, use latest
                if [ "$tag" == "Singularity" ]; then
                    tag=latest
                fi
                # Build the container and name by tag
                echo "Tag is $tag."
                container="$repo:$tag.sif"
                singularity build --fakeroot container.sif "$recipe"
                if [ "$?" == "0" ]; then
                    echo "Successfully built container $container."                
                    mv container.sif "$container"
                else
                    echo "There was an issue building $container."          
                fi                
            done
      - name: Run Additional Tests
        run: |
          echo "Run any additional tests here."
